spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: micoccimirko7@gmail.com
    password: botwalyxduwrxgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
